# Generated by Django 3.2.20 on 2023-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='CAT',
            field=models.ManyToManyField(blank=True, null=True, to='main.category'),
        ),
        migrations.DeleteModel(
            name='Categoryhasitem',
        ),
    ]
