# Generated by Django 3.2.20 on 2023-07-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230725_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CAT',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='main.category'),
        ),
    ]
