# Generated by Django 3.2.20 on 2023-07-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(blank=True, verbose_name='контакты')),
            ],
        ),
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название блока', max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='static\\media\\img')),
                ('is_img', models.BooleanField(default=False)),
                ('pro', models.ManyToManyField(blank=True, null=True, related_name='products', to='main.product')),
            ],
        ),
    ]
