# Generated by Django 3.2.20 on 2023-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_block_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='Название', max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+700000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='town',
            field=models.CharField(default='адрес проживания', max_length=200),
        ),
    ]
