# Generated by Django 3.2.20 on 2023-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230726_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shown',
            field=models.BooleanField(default=True, verbose_name='показать'),
        ),
    ]
