# Generated by Django 3.2.20 on 2023-08-03 14:47

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_shown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='was_basket',
        ),
        migrations.AddField(
            model_name='customuser',
            name='was_basket',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
