# Generated by Django 3.2.20 on 2023-08-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230803_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
