# Generated by Django 3.2.20 on 2023-08-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230805_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='host_of_email', max_length=150, verbose_name='имя-константа')),
                ('email', models.CharField(db_index=True, max_length=150, verbose_name='почта')),
                ('password', models.CharField(db_index=True, max_length=150, verbose_name='пароль')),
                ('a_password', models.CharField(db_index=True, default='пароль для рассылки смс', max_length=150, verbose_name='пароль sms рассылки')),
                ('a_email', models.CharField(db_index=True, default='почта для рассылки смс', max_length=150, verbose_name='почта sms рассылки')),
            ],
        ),
    ]
