# Generated by Django 3.2.20 on 2023-08-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_email_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='town',
            new_name='adress',
        ),
    ]
