# Generated by Django 3.2.20 on 2023-08-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20230817_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='all_size',
            field=models.CharField(default='перечисление размеров', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='tech_name',
            field=models.CharField(default='тех.название', max_length=200),
        ),
    ]
